### ISSUE TITLE
Discovery Service connectivity issues

### ISSUE THREAD

**Issue by smira** [siderolabs/discovery-service#49]
```[tasklist]
### Tasks
- [ ] https://github.com/siderolabs/discovery-service/issues/51
- [ ] Building a standalone load test cluster simulator
- [ ] https://github.com/siderolabs/discovery-service/issues/50
- [ ] Collecting debug logs with latest gRPC library (which has failures)
```

**Comment by smira** [comment]
I wonder if this is the root cause of our problems: https://github.com/grpc/grpc-go/pull/6834

**Comment by smira** [comment]
#50 was verified to fix the observed issue.
